/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  include\common\MotionProfiles.h
 *  model: motion_stack
 *  expmt: motion_stack
 *  date:  October 17, 2012
 *  time:  12:46:40 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.4.1
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
