"<?xml version=\"1.0\" ?>\n<!-- ===================================================================================\
  \ -->\n<!-- |    This document was autogenerated by xacro from /home/nicolapiccinelli/Workspace/youbot-ros-pkg/youbot_common/youbot_description/robots/youbot.urdf.xacro\
  \ | -->\n<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                \
  \                 | -->\n<!-- ===================================================================================\
  \ -->\n<robot name=\"youbot\" xmlns:controller=\"http://playerstage.sourceforge.net/gazebo/xmlschema/#controller\"\
  \ xmlns:interface=\"http://playerstage.sourceforge.net/gazebo/xmlschema/#interface\"\
  \ xmlns:sensor=\"http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor\" xmlns:xacro=\"\
  http://ros.org/wiki/xacro\">\n  <!-- The following included files set up definitions\
  \ of parts of the robot body -->\n  <!-- misc common stuff? -->\n  <!-- youbot base\
  \ -->\n  <!-- youbot plate -->\n  <!-- youbot arm -->\n  <!-- youbot gripper -->\n\
  \  <!-- generic simulator_gazebo plugins for starting mechanism control, ros time,\
  \ ros battery -->\n  <gazebo>\n    <plugin filename=\"libgazebo_ros_controller_manager.so\"\
  \ name=\"gazebo_ros_controller_manager\">\n      <alwaysOn>true</alwaysOn>\n   \
  \   <updateRate>1000.0</updateRate>\n    </plugin>\n    <plugin filename=\"libgazebo_ros_power_monitor.so\"\
  \ name=\"gazebo_ros_power_monitor_controller\">\n      <alwaysOn>true</alwaysOn>\n\
  \      <updateRate>1.0</updateRate>\n      <timeout>5</timeout>\n      <interface:audio\
  \ name=\"power_monitor_dummy_interface\"/>\n      <powerStateTopic>power_state</powerStateTopic>\n\
  \      <powerStateRate>10.0</powerStateRate>\n      <fullChargeCapacity>87.78</fullChargeCapacity>\n\
  \      <dischargeRate>-474</dischargeRate>\n      <chargeRate>525</chargeRate>\n\
  \      <dischargeVoltage>15.52</dischargeVoltage>\n      <chargeVoltage>16.41</chargeVoltage>\n\
  \    </plugin>\n  </gazebo>\n  <!-- materials for visualization -->\n  <material\
  \ name=\"Orange\">\n    <color rgba=\"1.0 0.4 0.0 1.0\"/>\n  </material>\n  <material\
  \ name=\"Grey\">\n    <color rgba=\"0.7 0.7 0.7 1.0\"/>\n  </material>\n  <material\
  \ name=\"DarkGrey\">\n    <color rgba=\"0.3 0.3 0.3 1.0\"/>\n  </material>\n  <material\
  \ name=\"White\">\n    <color rgba=\"1.0 1.0 1.0 1.0\"/>\n  </material>\n  <material\
  \ name=\"Black\">\n    <color rgba=\"0.0 0.0 0.0 1.0\"/>\n  </material>\n  <material\
  \ name=\"Red\">\n    <color rgba=\"1.0 0.0 0.0 1.0\"/>\n  </material>\n  <material\
  \ name=\"Green\">\n    <color rgba=\"0.0 1.0 0.0 1.0\"/>\n  </material>\n  <!--\
  \ Now we can start using the macros included above to define the actual youbot -->\n\
  \  <!-- The first use of a macro.  This one was defined in base.urdf.xacro above.\n\
  \       A macro like this will expand to a set of link and joint definitions, and\
  \ to additional\n       Gazebo-related extensions (sensor plugins, etc).  The macro\
  \ takes an argument, name, \n       that equals \"base\", and uses it to generate\
  \ names for its component links and joints \n       (e.g., base_link).  The included\
  \ origin block is also an argument to the macro.  By convention, \n       the origin\
  \ block defines where the component is w.r.t its parent (in this case the parent\
  \ \n       is the world frame). For more, see http://www.ros.org/wiki/xacro -->\n\
  \  <!-- foot for arm-->\n  <link name=\"base_footprint\">\n    <inertial>\n    \
  \  <mass value=\"0.1\"/>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 -0.05\"/>\n    \
  \  <inertia ixx=\"1.0\" ixy=\"0.0\" ixz=\"0.0\" iyy=\"1.0\" iyz=\"0.0\" izz=\"1.0\"\
  />\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n\
  \      <geometry>\n        <box size=\"0.001 0.001 0.001\"/>\n      </geometry>\n\
  \      <material name=\"Red\"/>\n    </visual>\n    <collision>\n      <origin rpy=\"\
  0 0 0\" xyz=\"0 0 -0.05\"/>\n      <geometry>\n        <box size=\"0.001 0.001 0.001\"\
  />\n      </geometry>\n    </collision>\n  </link>\n  <joint name=\"base_footprint_joint\"\
  \ type=\"fixed\">\n    <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n    <child link=\"\
  base_link\"/>\n    <parent link=\"base_footprint\"/>\n  </joint>\n  <link name=\"\
  base_link\">\n    <inertial>\n      <mass value=\"22.0\"/>\n      <origin xyz=\"\
  0 0 0\"/>\n      <inertia ixx=\"5.652232699207\" ixy=\"-0.009719934438\" ixz=\"\
  1.293988226423\" iyy=\"5.669473158652\" iyz=\"-0.007379583694\" izz=\"3.683196351726\"\
  />\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n\
  \      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_base/base.dae\"\
  />\n      </geometry>\n      <material name=\"DarkGrey\"/>\n    </visual>\n    <collision>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <!--<box\
  \ size=\"${base_size_x} ${base_size_y} ${base_size_z}\" />-->\n        <mesh filename=\"\
  package://youbot_description/meshes/youbot_base/base_convex.dae\"/>\n      </geometry>\n\
  \    </collision>\n  </link>\n  <joint name=\"base_laser_front_hokuyo_urg04_laser_joint\"\
  \ type=\"fixed\">\n    <axis xyz=\"0 1 0\"/>\n    <origin rpy=\"0 0 0\" xyz=\"0.3\
  \ 0 -0.03\"/>\n    <parent link=\"base_link\"/>\n    <child link=\"base_laser_front_link\"\
  />\n  </joint>\n  <link name=\"base_laser_front_link\" type=\"laser\">\n    <inertial>\n\
  \      <mass value=\"0.16\"/>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n   \
  \   <inertia ixx=\"0.1\" ixy=\"0\" ixz=\"0\" iyy=\"0.1\" iyz=\"0\" izz=\"0.1\"/>\n\
  \    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n  \
  \    <geometry>\n        <mesh filename=\"package://youbot_description/meshes/sensors/hokuyo.dae\"\
  />\n      </geometry>\n      <material name=\"DarkGrey\"/>\n    </visual>\n    <collision>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"\
  package://youbot_description/meshes/sensors/hokuyo_convex.dae\"/>\n      </geometry>\n\
  \    </collision>\n  </link>\n  <gazebo reference=\"base_laser_front_link\">\n \
  \   <sensor name=\"base_laser_front\" type=\"ray\">\n      <always_on>true</always_on>\n\
  \      <update_rate>10</update_rate>\n      <pose>0 0 0 0 0 0</pose>\n      <visualize>false</visualize>\n\
  \      <ray>\n        <scan>\n          <horizontal>\n            <samples>150</samples>\n\
  \            <resolution>1.0</resolution>\n            <min_angle>-1.57</min_angle>\n\
  \            <max_angle>1.57</max_angle>\n          </horizontal>\n        </scan>\n\
  \        <range>\n          <min>0.05</min>\n          <max>5.6</max>\n        \
  \  <resolution>0.36</resolution>\n        </range>\n      </ray>\n      <plugin\
  \ filename=\"libgazebo_ros_laser.so\" name=\"gazebo_ros_base_laser_front_controller\"\
  >\n        <gaussianNoise>0.005</gaussianNoise>\n        <alwaysOn>true</alwaysOn>\n\
  \        <updateRate>10</updateRate>\n        <topicName>scan_front</topicName>\n\
  \        <frameName>/base_laser_front_link</frameName>\n      </plugin>\n    </sensor>\n\
  \  </gazebo>\n  <joint name=\"caster_joint_fl\" type=\"continuous\">\n    <origin\
  \ rpy=\"0 0 0\" xyz=\"0.228 0.158 -0.034\"/>\n    <axis xyz=\"0 0 1\"/>\n    <limit\
  \ effort=\"30\" velocity=\"10\"/>\n    <dynamics damping=\"1.0\" friction=\"1.0\"\
  />\n    <safety_controller k_velocity=\"10.0\"/>\n    <parent link=\"base_link\"\
  />\n    <child link=\"caster_link_fl\"/>\n  </joint>\n  <link name=\"caster_link_fl\"\
  >\n    <inertial>\n      <mass value=\"0.1\"/>\n      <origin xyz=\"0 0 0\"/>\n\
  \      <inertia ixx=\"0.012411765597\" ixy=\"-0.000711733678\" ixz=\"0.00050272983\"\
  \ iyy=\"0.015218160428\" iyz=\"-0.000004273467\" izz=\"0.011763977943\"/>\n    </inertial>\n\
  \  </link>\n  <joint name=\"wheel_joint_fl\" type=\"continuous\">\n    <axis xyz=\"\
  0 1 0\"/>\n    <limit effort=\"30\" velocity=\"10\"/>\n    <origin rpy=\"0 0 0\"\
  \ xyz=\"0.0 0.0 0.0\"/>\n    <parent link=\"caster_link_fl\"/>\n    <dynamics damping=\"\
  1.0\" friction=\"1.0\"/>\n    <safety_controller k_velocity=\"10.0\"/>\n    <child\
  \ link=\"wheel_link_fl\"/>\n  </joint>\n  <link name=\"wheel_link_fl\">\n    <inertial>\n\
  \      <mass value=\"0.4\"/>\n      <origin xyz=\"0 0 0\"/>\n      <inertia ixx=\"\
  0.012411765597\" ixy=\"-0.000711733678\" ixz=\"0.00050272983\" iyy=\"0.015218160428\"\
  \ iyz=\"-0.000004273467\" izz=\"0.011763977943\"/>\n    </inertial>\n    <visual>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <!--<mesh filename=\"package://youbot_description/meshes/youbot_base/youbot_wheel.stl\"\
  \ />-->\n      <geometry>\n        <sphere radius=\"0.05\"/>\n      </geometry>\n\
  \      <material name=\"Orange\"/>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"1.57079632679 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <cylinder\
  \ length=\"0.05\" radius=\"0.05\"/>\n      </geometry>\n    </collision>\n  </link>\n\
  \  <joint name=\"caster_joint_fr\" type=\"continuous\">\n    <origin rpy=\"0 0 0\"\
  \ xyz=\"0.228 -0.158 -0.034\"/>\n    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"\
  30\" velocity=\"10\"/>\n    <dynamics damping=\"1.0\" friction=\"1.0\"/>\n    <safety_controller\
  \ k_velocity=\"10.0\"/>\n    <parent link=\"base_link\"/>\n    <child link=\"caster_link_fr\"\
  />\n  </joint>\n  <link name=\"caster_link_fr\">\n    <inertial>\n      <mass value=\"\
  0.1\"/>\n      <origin xyz=\"0 0 0\"/>\n      <inertia ixx=\"0.012411765597\" ixy=\"\
  -0.000711733678\" ixz=\"0.00050272983\" iyy=\"0.015218160428\" iyz=\"-0.000004273467\"\
  \ izz=\"0.011763977943\"/>\n    </inertial>\n  </link>\n  <joint name=\"wheel_joint_fr\"\
  \ type=\"continuous\">\n    <axis xyz=\"0 1 0\"/>\n    <limit effort=\"30\" velocity=\"\
  10\"/>\n    <dynamics damping=\"1.0\" friction=\"1.0\"/>\n    <safety_controller\
  \ k_velocity=\"10.0\"/>\n    <origin rpy=\"0 0 0\" xyz=\"0.0 0.0 0.0\"/>\n    <parent\
  \ link=\"caster_link_fr\"/>\n    <child link=\"wheel_link_fr\"/>\n  </joint>\n \
  \ <link name=\"wheel_link_fr\">\n    <inertial>\n      <mass value=\"0.4\"/>\n \
  \     <origin xyz=\"0 0 0\"/>\n      <inertia ixx=\"0.012411765597\" ixy=\"-0.000711733678\"\
  \ ixz=\"0.00050272983\" iyy=\"0.015218160428\" iyz=\"-0.000004273467\" izz=\"0.011763977943\"\
  />\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n\
  \      <geometry>\n        <!--<mesh filename=\"package://youbot_description/meshes/youbot_base/youbot_wheel.stl\"\
  \ />-->\n        <sphere radius=\"0.05\"/>\n      </geometry>\n      <material name=\"\
  Orange\"/>\n    </visual>\n    <collision>\n      <origin rpy=\"1.57079632679 0\
  \ 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <cylinder length=\"0.05\" radius=\"\
  0.05\"/>\n      </geometry>\n    </collision>\n  </link>\n  <joint name=\"caster_joint_bl\"\
  \ type=\"continuous\">\n    <origin rpy=\"0 0 0\" xyz=\"-0.228 0.158 -0.034\"/>\n\
  \    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"30\" velocity=\"10\"/>\n    <dynamics\
  \ damping=\"1.0\" friction=\"1.0\"/>\n    <safety_controller k_velocity=\"10.0\"\
  />\n    <parent link=\"base_link\"/>\n    <child link=\"caster_link_bl\"/>\n  </joint>\n\
  \  <link name=\"caster_link_bl\">\n    <inertial>\n      <mass value=\"0.1\"/>\n\
  \      <origin xyz=\"0 0 0\"/>\n      <inertia ixx=\"0.012411765597\" ixy=\"-0.000711733678\"\
  \ ixz=\"0.00050272983\" iyy=\"0.015218160428\" iyz=\"-0.000004273467\" izz=\"0.011763977943\"\
  />\n    </inertial>\n  </link>\n  <joint name=\"wheel_joint_bl\" type=\"continuous\"\
  >\n    <axis xyz=\"0 1 0\"/>\n    <limit effort=\"10\" velocity=\"10\"/>\n    <limit\
  \ effort=\"30\" velocity=\"10\"/>\n    <dynamics damping=\"1.0\" friction=\"1.0\"\
  />\n    <safety_controller k_velocity=\"10.0\"/>\n    <origin rpy=\"0 0 0\" xyz=\"\
  0.0 0.0 0.0\"/>\n    <parent link=\"caster_link_bl\"/>\n    <child link=\"wheel_link_bl\"\
  />\n  </joint>\n  <link name=\"wheel_link_bl\">\n    <inertial>\n      <mass value=\"\
  0.4\"/>\n      <origin xyz=\"0 0 0\"/>\n      <inertia ixx=\"0.012411765597\" ixy=\"\
  -0.000711733678\" ixz=\"0.00050272983\" iyy=\"0.015218160428\" iyz=\"-0.000004273467\"\
  \ izz=\"0.011763977943\"/>\n    </inertial>\n    <visual>\n      <origin rpy=\"\
  0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <!--<mesh filename=\"package://youbot_description/meshes/youbot_base/youbot_wheel.stl\"\
  \ />-->\n        <sphere radius=\"0.05\"/>\n      </geometry>\n      <material name=\"\
  Orange\"/>\n    </visual>\n    <collision>\n      <origin rpy=\"1.57079632679 0\
  \ 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <cylinder length=\"0.05\" radius=\"\
  0.05\"/>\n      </geometry>\n    </collision>\n  </link>\n  <joint name=\"caster_joint_br\"\
  \ type=\"continuous\">\n    <origin rpy=\"0 0 0\" xyz=\"-0.228 -0.158 -0.034\"/>\n\
  \    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"30\" velocity=\"10\"/>\n    <dynamics\
  \ damping=\"1.0\" friction=\"1.0\"/>\n    <safety_controller k_velocity=\"10.0\"\
  />\n    <parent link=\"base_link\"/>\n    <child link=\"caster_link_br\"/>\n  </joint>\n\
  \  <link name=\"caster_link_br\">\n    <inertial>\n      <mass value=\"0.1\"/>\n\
  \      <origin xyz=\"0 0 0\"/>\n      <inertia ixx=\"0.012411765597\" ixy=\"-0.000711733678\"\
  \ ixz=\"0.00050272983\" iyy=\"0.015218160428\" iyz=\"-0.000004273467\" izz=\"0.011763977943\"\
  />\n    </inertial>\n  </link>\n  <joint name=\"wheel_joint_br\" type=\"continuous\"\
  >\n    <axis xyz=\"0 1 0\"/>\n    <limit effort=\"30\" velocity=\"10\"/>\n    <dynamics\
  \ damping=\"1.0\" friction=\"1.0\"/>\n    <safety_controller k_velocity=\"10.0\"\
  />\n    <origin rpy=\"0 0 0\" xyz=\"0.0 0.0 0.0\"/>\n    <parent link=\"caster_link_br\"\
  />\n    <child link=\"wheel_link_br\"/>\n  </joint>\n  <link name=\"wheel_link_br\"\
  >\n    <inertial>\n      <mass value=\"0.4\"/>\n      <origin xyz=\"0 0 0\"/>\n\
  \      <inertia ixx=\"0.012411765597\" ixy=\"-0.000711733678\" ixz=\"0.00050272983\"\
  \ iyy=\"0.015218160428\" iyz=\"-0.000004273467\" izz=\"0.011763977943\"/>\n    </inertial>\n\
  \    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n \
  \       <!--<mesh filename=\"package://youbot_description/meshes/youbot_base/youbot_wheel.stl\"\
  \ />-->\n        <sphere radius=\"0.05\"/>\n      </geometry>\n      <material name=\"\
  Orange\"/>\n    </visual>\n    <collision>\n      <origin rpy=\"1.57079632679 0\
  \ 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <cylinder length=\"0.05\" radius=\"\
  0.05\"/>\n      </geometry>\n    </collision>\n  </link>\n  <gazebo reference=\"\
  youbot_base\">\n    <material value=\"youbot/DarkGrey\"/>\n  </gazebo>\n  <gazebo\
  \ reference=\"wheel_link_fl\">\n    <material value=\"youbot/Orange\"/>\n  </gazebo>\n\
  \  <gazebo reference=\"caster_link_fl\">\n    <material value=\"youbot/Orange\"\
  />\n  </gazebo>\n  <gazebo reference=\"wheel_link_fr\">\n    <material value=\"\
  youbot/Orange\"/>\n  </gazebo>\n  <gazebo reference=\"caster_link_fr\">\n    <material\
  \ value=\"youbot/Orange\"/>\n  </gazebo>\n  <gazebo reference=\"wheel_link_bl\"\
  >\n    <material value=\"youbot/Orange\"/>\n  </gazebo>\n  <gazebo reference=\"\
  caster_link_bl\">\n    <material value=\"youbot/Orange\"/>\n  </gazebo>\n  <gazebo\
  \ reference=\"wheel_link_br\">\n    <material value=\"youbot/Orange\"/>\n  </gazebo>\n\
  \  <gazebo reference=\"caster_link_br\">\n    <material value=\"youbot/Orange\"\
  />\n  </gazebo>\n  <gazebo>\n    <plugin filename=\"libgazebo_ros_p3d.so\" name=\"\
  p3d_base_controller\">\n      <alwaysOn>true</alwaysOn>\n      <updateRate>100.0</updateRate>\n\
  \      <bodyName>base_link</bodyName>\n      <topicName>base_pose_ground_truth</topicName>\n\
  \      <gaussianNoise>0.01</gaussianNoise>\n      <frameName>map</frameName>\n \
  \     <xyzOffsets>25.7 25.7 0</xyzOffsets>\n      <!-- initialize odometry for fake\
  \ localization-->\n      <rpyOffsets>0 0 0</rpyOffsets>\n    </plugin>\n    <canonicalBody>base_footprint</canonicalBody>\n\
  \  </gazebo>\n  <transmission name=\"wheel_trans_fl\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"wheel_motor_fl\"/>\n    <joint name=\"wheel_joint_fl\"/>\n\
  \    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"caster_trans_fl\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"caster_motor_fl\"/>\n    <joint name=\"caster_joint_fl\"\
  />\n    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"wheel_trans_fr\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"wheel_motor_fr\"/>\n    <joint name=\"wheel_joint_fr\"/>\n\
  \    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"caster_trans_fr\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"caster_motor_fr\"/>\n    <joint name=\"caster_joint_fr\"\
  />\n    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"wheel_trans_bl\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"wheel_motor_bl\"/>\n    <joint name=\"wheel_joint_bl\"/>\n\
  \    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"caster_trans_bl\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"caster_motor_bl\"/>\n    <joint name=\"caster_joint_bl\"\
  />\n    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"wheel_trans_br\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"wheel_motor_br\"/>\n    <joint name=\"wheel_joint_br\"/>\n\
  \    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <transmission name=\"caster_trans_br\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"caster_motor_br\"/>\n    <joint name=\"caster_joint_br\"\
  />\n    <mechanicalReduction>79.2380952381</mechanicalReduction>\n  </transmission>\n\
  \  <joint name=\"plate_joint\" type=\"fixed\">\n    <origin rpy=\"0 0 0\" xyz=\"\
  -0.159 0 0.046\"/>\n    <parent link=\"base_link\"/>\n    <child link=\"plate_link\"\
  />\n  </joint>\n  <link name=\"plate_link\">\n    <inertial>\n      <origin rpy=\"\
  0 0 0\" xyz=\"0 0 0\"/>\n      <mass value=\"1\"/>\n      <inertia ixx=\"0.01\"\
  \ ixy=\"0\" ixz=\"0\" iyy=\"0.01\" iyz=\"0\" izz=\"0.01\"/>\n    </inertial>\n \
  \   <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n  \
  \      <mesh filename=\"package://youbot_description/meshes/youbot_plate/plate.dae\"\
  />\n      </geometry>\n      <material name=\"DarkGrey\"/>\n    </visual>\n    <collision>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"\
  package://youbot_description/meshes/youbot_plate/plate_convex.dae\"/>\n      </geometry>\n\
  \    </collision>\n  </link>\n  <joint name=\"arm_joint_0\" type=\"fixed\">\n  \
  \  <origin rpy=\"0 0 0\" xyz=\"0.143 0 0.046\"/>\n    <parent link=\"base_link\"\
  />\n    <child link=\"arm_link_0\"/>\n  </joint>\n  <link name=\"arm_link_0\">\n\
  \    <inertial>\n      <!--<origin xyz=\"0.023 0 0.006\" rpy=\"0 0 0\"/>-->\n  \
  \    <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <mass value=\"0.845\"/>\n    \
  \  <inertia ixx=\"0.01\" ixy=\"0\" ixz=\"0\" iyy=\"0.01\" iyz=\"0\" izz=\"0.01\"\
  />\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n\
  \      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm0.dae\"\
  />\n      </geometry>\n      <material name=\"DarkGrey\"/>\n    </visual>\n    <collision>\n\
  \      <!--<origin xyz=\"0.023 0 0.006\" rpy=\"0 0 0\"/>-->\n      <origin rpy=\"\
  0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm0_convex.dae\"\
  />\n        <!--<cylinder length=\"0.078\" radius=\"0.093\"/>-->\n      </geometry>\n\
  \    </collision>\n  </link>\n  <joint name=\"arm_joint_1\" type=\"revolute\">\n\
  \    <origin rpy=\"0 0 2.96705972839\" xyz=\"0.024 0 0.096\"/>\n    <parent link=\"\
  arm_link_0\"/>\n    <child link=\"arm_link_1\"/>\n    <axis xyz=\"0 0 -1\"/>\n \
  \   <!--<calibration rising=\"${arm_1_ref}\" falling=\"${arm_1_ref}\"/>-->\n   \
  \ <dynamics damping=\"1\" friction=\"1\"/>\n    <!-- damping - N*s/m, N*s*m/rad\
  \ -->\n    <!-- friction - N, N*m -->\n    <limit effort=\"9.5\" lower=\"0\" upper=\"\
  5.89921287174\" velocity=\"1.57079632679\"/>\n    <!--effort - N, N*m-->\n    <!--velocity\
  \ - m/s, rad/s-->\n    <safety_controller k_position=\"20\" k_velocity=\"1.51197195937\"\
  \ soft_lower_limit=\"0.001\" soft_upper_limit=\"5.89821287174\"/>\n    <!--k_position\
  \ N/m, N/rad-->\n    <!--k_velocity N*s/m, N*s*m/rad-->\n    <!--for details: http://www.ros.org/wiki/pr2_controller_manager/safety_limits-->\n\
  \  </joint>\n  <link name=\"arm_link_1\">\n    <inertial>\n      <mass value=\"\
  2.412\"/>\n      <origin rpy=\"0 0 0\" xyz=\"0.01489 0.00213 0.00213\"/>\n     \
  \ <inertia ixx=\"0.003863\" ixy=\"-0.000979\" ixz=\"0.000000\" iyy=\"0.006196\"\
  \ iyz=\"0.000000\" izz=\"0.006369\"/>\n    </inertial>\n    <visual>\n      <origin\
  \ rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm1.dae\"\
  />\n      </geometry>\n      <!--<material name=\"Orange\" />-->\n    </visual>\n\
  \    <collision>\n      <!--<origin xyz=\"0 0 -0.003\" rpy=\"0 0 0\" />-->\n   \
  \   <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"\
  package://youbot_description/meshes/youbot_arm/arm1_convex.dae\"/>\n        <!--<cylinder\
  \ length=\"0.102\" radius=\"0.080\"/>-->\n      </geometry>\n    </collision>\n\
  \  </link>\n  <joint name=\"arm_joint_2\" type=\"revolute\">\n    <origin rpy=\"\
  0 -1.1344640138 0\" xyz=\"0.033 0 0.019\"/>\n    <parent link=\"arm_link_1\"/>\n\
  \    <child link=\"arm_link_2\"/>\n    <axis xyz=\"0 1 0\"/>\n    <!--<calibration\
  \ rising=\"${arm_2_ref}\" falling=\"${arm_2_ref}\"/>-->\n    <dynamics damping=\"\
  1\" friction=\"1\"/>\n    <limit effort=\"9.5\" lower=\"0\" upper=\"2.70526034059\"\
  \ velocity=\"1.57079632679\"/>\n    <safety_controller k_position=\"20\" k_velocity=\"\
  6.04788783749\" soft_lower_limit=\"0.001\" soft_upper_limit=\"2.70426034059\"/>\n\
  \  </joint>\n  <link name=\"arm_link_2\">\n    <inertial>\n      <mass value=\"\
  1.155\"/>\n      <origin rpy=\"0 0 0\" xyz=\"0.10453 0.0017 -0.00297\"/>\n     \
  \ <inertia ixx=\"0.000823\" ixy=\"0.000000\" ixz=\"-0.000000\" iyy=\"0.004447\"\
  \ iyz=\"0.000000\" izz=\"0.004439\"/>\n    </inertial>\n    <visual>\n      <origin\
  \ rpy=\"0 0 0\" xyz=\"0 -0.032 0.078\"/>\n      <geometry>\n        <mesh filename=\"\
  package://youbot_description/meshes/youbot_arm/arm2.dae\"/>\n      </geometry>\n\
  \      <material name=\"Orange\"/>\n    </visual>\n    <collision>\n      <!--<origin\
  \ xyz=\"0.001 -0.041 0.074\" rpy=\"0 0 0\" />-->\n      <origin rpy=\"0 0 0\" xyz=\"\
  0 -0.032 0.078\"/>\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm2_convex.dae\"\
  />\n        <!--<box size=\"0.074 0.082 0.222\"/>-->\n      </geometry>\n    </collision>\n\
  \  </link>\n  <joint name=\"arm_joint_3\" type=\"revolute\">\n    <origin rpy=\"\
  0 2.54818070791 0\" xyz=\"0.000 0.000 0.155\"/>\n    <parent link=\"arm_link_2\"\
  />\n    <child link=\"arm_link_3\"/>\n    <axis xyz=\"0 1 0\"/>\n    <dynamics damping=\"\
  1\" friction=\"1\"/>\n    <limit effort=\"6.0\" lower=\"-5.18362787842\" upper=\"\
  0\" velocity=\"1.57079632679\"/>\n    <safety_controller k_position=\"20\" k_velocity=\"\
  50\" soft_lower_limit=\"-5.18262787842\" soft_upper_limit=\"-0.001\"/>\n  </joint>\n\
  \  <link name=\"arm_link_3\">\n    <inertial>\n      <mass value=\"0.934\"/>\n \
  \     <origin rpy=\"0 0 0\" xyz=\"0.0001 0.0967 0.02107\"/>\n      <inertia ixx=\"\
  0.002459\" ixy=\"0.000000\" ixz=\"0.000000\" iyy=\"0.002571\" iyz=\"-0.000000\"\
  \ izz=\"0.000535\"/>\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\"\
  \ xyz=\"0.000 0.028 0.079\"/>\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm3.dae\"\
  />\n      </geometry>\n      <material name=\"Orange\"/>\n    </visual>\n    <collision>\n\
  \      <!--<origin xyz=\"0.000 0.025 0.067\" rpy=\"0 0 0\" />-->\n      <origin\
  \ rpy=\"0 0 0\" xyz=\"0.000 0.028 0.079\"/>\n      <geometry>\n        <mesh filename=\"\
  package://youbot_description/meshes/youbot_arm/arm3_convex.dae\"/>\n        <!--<box\
  \ size=\"0.064 0.054 0.192\"/>-->\n      </geometry>\n    </collision>\n  </link>\n\
  \  <joint name=\"arm_joint_4\" type=\"revolute\">\n    <origin rpy=\"0 -1.78896248329\
  \ 0\" xyz=\"0.000 0.000 0.135\"/>\n    <parent link=\"arm_link_3\"/>\n    <child\
  \ link=\"arm_link_4\"/>\n    <axis xyz=\"0 1 0\"/>\n    <!--<calibration rising=\"\
  ${arm_4_ref}\" falling=\"${arm_4_ref}\"/>-->\n    <dynamics damping=\"1\" friction=\"\
  1\"/>\n    <limit effort=\"2.0\" lower=\"0\" upper=\"3.57792496659\" velocity=\"\
  1.57079632679\"/>\n    <safety_controller k_position=\"20\" k_velocity=\"100\" soft_lower_limit=\"\
  0\" soft_upper_limit=\"3.57692496659\"/>\n  </joint>\n  <link name=\"arm_link_4\"\
  >\n    <inertial>\n      <mass value=\"0.877\"/>\n      <origin rpy=\"0 0 0\" xyz=\"\
  0.00011 0.05103 -0.02319\"/>\n      <inertia ixx=\"0.000869\" ixy=\"0.000000\" ixz=\"\
  -0.000000\" iyy=\"0.001173\" iyz=\"-0.000231\" izz=\"0.001091\"/>\n    </inertial>\n\
  \    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 -0.010 0.029\"/>\n      <geometry>\n\
  \        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm4.dae\"\
  />\n      </geometry>\n      <material name=\"Orange\"/>\n    </visual>\n    <collision>\n\
  \      <!--<origin xyz=\"0 0 0.026\" rpy=\"0 0 0\" />-->\n      <origin rpy=\"0\
  \ 0 0\" xyz=\"0 -0.010 0.029\"/>\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm4_convex.dae\"\
  />\n        <!--<box size=\"0.058 0.100 0.118\"/>-->\n      </geometry>\n    </collision>\n\
  \  </link>\n  <joint name=\"arm_joint_5\" type=\"revolute\">\n    <origin rpy=\"\
  0 0 2.92342649709\" xyz=\"-0.002 0 0.130\"/>\n    <parent link=\"arm_link_4\"/>\n\
  \    <child link=\"arm_link_5\"/>\n    <axis xyz=\"0 0 -1\"/>\n    <!--<calibration\
  \ rising=\"${arm_5_ref}\" falling=\"${arm_5_ref}\"/>-->\n    <dynamics damping=\"\
  1\" friction=\"1\"/>\n    <limit effort=\"1\" lower=\"0\" upper=\"5.84685299418\"\
  \ velocity=\"1.57079632679\"/>\n    <safety_controller k_position=\"20\" k_velocity=\"\
  100\" soft_lower_limit=\"0\" soft_upper_limit=\"5.84585299418\"/>\n  </joint>\n\
  \  <link name=\"arm_link_5\">\n    <inertial>\n      <mass value=\"0.251\"/>\n \
  \     <origin rpy=\"0 0 0\" xyz=\"0.0 0.00115 -0.01683\"/>\n      <inertia ixx=\"\
  0.000280\" ixy=\"0.000000\" ixz=\"0.000000\" iyy=\"0.000339\" iyz=\"0.000000\" izz=\"\
  0.000119\"/>\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"\
  0.003 0 -0.034\"/>\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm5.dae\"\
  />\n      </geometry>\n      <material name=\"DarkGrey\"/>\n    </visual>\n    <collision>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0.003 0 -0.034\"/>\n      <geometry>\n      \
  \  <mesh filename=\"package://youbot_description/meshes/youbot_arm/arm5_convex.dae\"\
  />\n        <!--<box size=\"0.054 0.096 0.030\"/>-->\n      </geometry>\n    </collision>\n\
  \  </link>\n  <gazebo reference=\"arm_link_0\">\n    <material value=\"youbot/DarkGrey\"\
  />\n    <turnGravityOff>false</turnGravityOff>\n  </gazebo>\n  <gazebo reference=\"\
  arm_link_1\">\n    <!--<material value=\"youbot/Orange\" />-->\n    <turnGravityOff>false</turnGravityOff>\n\
  \  </gazebo>\n  <gazebo reference=\"arm_link_2\">\n    <!--<material value=\"youbot/Orange\"\
  \ />-->\n    <turnGravityOff>false</turnGravityOff>\n  </gazebo>\n  <gazebo reference=\"\
  arm_link_3\">\n    <!--<material value=\"youbot/Orange\" />-->\n    <turnGravityOff>false</turnGravityOff>\n\
  \  </gazebo>\n  <gazebo reference=\"arm_link_4\">\n    <!--<material value=\"youbot/Orange\"\
  \ />-->\n    <turnGravityOff>false</turnGravityOff>\n  </gazebo>\n  <gazebo reference=\"\
  arm_link_5\">\n    <!--<material value=\"youbot/DarkGrey\" />-->\n    <turnGravityOff>false</turnGravityOff>\n\
  \  </gazebo>\n  <transmission name=\"arm_trans_1\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"arm_motor_1\"/>\n    <joint name=\"arm_joint_1\"/>\n   \
  \ <mechanicalReduction>1</mechanicalReduction>\n  </transmission>\n  <transmission\
  \ name=\"arm_trans_2\" type=\"pr2_mechanism_model/SimpleTransmission\">\n    <actuator\
  \ name=\"arm_motor_2\"/>\n    <joint name=\"arm_joint_2\"/>\n    <mechanicalReduction>1</mechanicalReduction>\n\
  \  </transmission>\n  <transmission name=\"arm_trans_3\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"arm_motor_3\"/>\n    <joint name=\"arm_joint_3\"/>\n   \
  \ <mechanicalReduction>1</mechanicalReduction>\n  </transmission>\n  <transmission\
  \ name=\"arm_trans_4\" type=\"pr2_mechanism_model/SimpleTransmission\">\n    <actuator\
  \ name=\"arm_motor_4\"/>\n    <joint name=\"arm_joint_4\"/>\n    <mechanicalReduction>1</mechanicalReduction>\n\
  \  </transmission>\n  <transmission name=\"arm_trans_5\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"arm_motor_5\"/>\n    <joint name=\"arm_joint_5\"/>\n   \
  \ <mechanicalReduction>1</mechanicalReduction>\n  </transmission>\n  <joint name=\"\
  gripper_palm_joint\" type=\"fixed\">\n    <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n\
  \    <parent link=\"arm_link_5\"/>\n    <child link=\"gripper_palm_link\"/>\n  </joint>\n\
  \  <link name=\"gripper_palm_link\">\n    <inertial>\n      <origin rpy=\"0 0 0\"\
  \ xyz=\"0 0 0\"/>\n      <mass value=\"0.1\"/>\n      <inertia ixx=\"0.01\" ixy=\"\
  0\" ixz=\"0\" iyy=\"0.01\" iyz=\"0\" izz=\"0.01\"/>\n    </inertial>\n    <visual>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"\
  package://youbot_description/meshes/youbot_gripper/palm.dae\"/>\n      </geometry>\n\
  \      <material name=\"Black\"/>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <!--<box size=\"0.050\
  \ 0.094 0.054\"/>-->\n        <mesh filename=\"package://youbot_description/meshes/youbot_gripper/palm_convex.dae\"\
  />\n      </geometry>\n    </collision>\n  </link>\n  <joint name=\"gripper_finger_joint_l\"\
  \ type=\"prismatic\">\n    <origin rpy=\"0 0 3.14159265359\" xyz=\"0.004 0.008 0.046\"\
  />\n    <parent link=\"gripper_palm_link\"/>\n    <child link=\"gripper_finger_link_l\"\
  />\n    <axis xyz=\"0 -1 0\"/>\n    <dynamics damping=\"1.0\" friction=\"1.0\"/>\n\
  \    <limit effort=\"1\" lower=\"0\" upper=\"0.0115\" velocity=\"0.1\"/>\n    <safety_controller\
  \ k_position=\"20\" k_velocity=\"25\" soft_lower_limit=\"0.001\" soft_upper_limit=\"\
  0.011\"/>\n  </joint>\n  <link name=\"gripper_finger_link_l\">\n    <inertial>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 -0.001 0\"/>\n      <mass value=\"0.01\"/>\n\
  \      <inertia ixx=\"0.01\" ixy=\"0\" ixz=\"0\" iyy=\"0.01\" iyz=\"0\" izz=\"0.01\"\
  />\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n\
  \      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_gripper/finger.dae\"\
  />\n      </geometry>\n      <material name=\"Black\"/>\n    </visual>\n    <collision>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n      <geometry>\n        <!--<box\
  \ size=\"0.014 0.020 0.046\"/>-->\n        <mesh filename=\"package://youbot_description/meshes/youbot_gripper/finger_convex.dae\"\
  />\n      </geometry>\n    </collision>\n  </link>\n  <joint name=\"gripper_finger_joint_r\"\
  \ type=\"prismatic\">\n    <origin rpy=\"0 0 0\" xyz=\"0.004 -0.008 0.046\"/>\n\
  \    <parent link=\"gripper_palm_link\"/>\n    <child link=\"gripper_finger_link_r\"\
  />\n    <axis xyz=\"0 -1 0\"/>\n    <dynamics damping=\"1.0\" friction=\"1.0\"/>\n\
  \    <limit effort=\"1\" lower=\"0\" upper=\"0.0115\" velocity=\"0.1\"/>\n    <safety_controller\
  \ k_position=\"20\" k_velocity=\"25\" soft_lower_limit=\"0.001\" soft_upper_limit=\"\
  0.011\"/>\n  </joint>\n  <link name=\"gripper_finger_link_r\">\n    <inertial>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0.000 -0.001 0\"/>\n      <mass value=\"0.01\"\
  />\n      <inertia ixx=\"0.01\" ixy=\"0\" ixz=\"0\" iyy=\"0.01\" iyz=\"0\" izz=\"\
  0.01\"/>\n    </inertial>\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"\
  />\n      <geometry>\n        <mesh filename=\"package://youbot_description/meshes/youbot_gripper/finger.dae\"\
  />\n      </geometry>\n      <material name=\"Black\"/>\n    </visual>\n    <collision>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0.000 0 0\"/>\n      <geometry>\n        <!--<box\
  \ size=\"0.014 0.020 0.046\"/>-->\n        <mesh filename=\"package://youbot_description/meshes/youbot_gripper/finger_convex.dae\"\
  />\n      </geometry>\n    </collision>\n  </link>\n  <gazebo reference=\"gripper_palm_link\"\
  >\n    <material>Gazebo/Black</material>\n    <turnGravityOff>false</turnGravityOff>\n\
  \    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"gripper_finger_l_link\"\
  >\n    <material>Gazebo/Black</material>\n    <turnGravityOff>false</turnGravityOff>\n\
  \    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"gripper_finger_r_link\"\
  >\n    <material>Gazebo/Black</material>\n    <turnGravityOff>false</turnGravityOff>\n\
  \    <selfCollide>true</selfCollide>\n  </gazebo>\n  <transmission name=\"gripper_finger_l_trans\"\
  \ type=\"pr2_mechanism_model/SimpleTransmission\">\n    <actuator name=\"gripper_finger_l_motor\"\
  />\n    <joint name=\"gripper_finger_joint_l\"/>\n    <mechanicalReduction>1</mechanicalReduction>\n\
  \  </transmission>\n  <transmission name=\"gripper_finger_r_trans\" type=\"pr2_mechanism_model/SimpleTransmission\"\
  >\n    <actuator name=\"gripper_finger_r_motor\"/>\n    <joint name=\"gripper_finger_joint_r\"\
  />\n    <mechanicalReduction>1</mechanicalReduction>\n  </transmission>\n</robot>\n\
  \n"

