SET(HILAS_BASE "$ENV{HILAS_HOME}/hilas")

SET(HILAS_COMMON "${HILAS_BASE}/common")
SET(HILAS_INTERFACES "${HILAS_BASE}/common/interfaces")
SET(HILAS_DEFINITIONS "${HILAS_BASE}/definitions")
SET(HILAS_ROBOTS "${HILAS_BASE}/robots")
SET(HILAS_SIM "${HILAS_BASE}/simulator")
SET(HILAS_HL "${HILAS_BASE}/hl")
SET(HILAS_CONFIG "${HILAS_BASE}/config")