SET(HILAS_COMMON "$ENV{HILAS_HOME}/hilas/common/")
SET(HILAS_INTERFACES "${HILAS_COMMON}/interfaces")
SET(HILAS_DEFINITIONS "$ENV{HILAS_HOME}/definitions")
SET(HILAS_ROBOTS "$ENV{HILAS_HOME}/robots")
SET(HILAS_ROBOTS "$ENV{HILAS_HOME}/simulator")
SET(HILAS_HL "$ENV{HILAS_HOME}/hl")
SET(HILAS_CONFIG "$ENV{HILAS_HOME}/config")

INCLUDE_DIRECTORIES(${HILAS_DEFINITIONS})